export const FAMOUS_QUOTES = [
  "It was the best of times, it was the worst of times.",
  "Not all those who wander are lost.",
  "So we beat on, boats against the current.",
  "I am no bird; and no net ensnares me.",
  "Tomorrow is another day.",
  "Call me Ishmael.",
  "The rest is silence.",
  "To be, or not to be: that is the question.",
  "Brevity is the soul of wit.",
  "Parting is such sweet sorrow.",
  "If music be the food of love, play on.",
  "Lord, what fools these mortals be!",
  "The lady doth protest too much, methinks.",
  "The course of true love never did run smooth.",
  "What's in a name? That which we call a rose.",
  "Some are born great, some achieve greatness.",
  "Uneasy lies the head that wears a crown.",
  "Cowards die many times before their deaths.",
  "We are such stuff as dreams are made on.",
  "I wandered lonely as a cloud.",
  "Hope is the thing with feathers.",
  "Tell all the truth but tell it slant.",
  "Do I dare disturb the universe?",
  "I have measured out my life with coffee spoons.",
  "April is the cruellest month.",
  "Things fall apart; the centre cannot hold.",
  "Big Brother is watching you.",
  "Who controls the past controls the future.",
  "War is peace. Freedom is slavery.",
  "All that is gold does not glitter.",
  "There and back again.",
  "After all this time? Always.",
  "Fear cuts deeper than swords.",
  "The man in black fled across the desert.",
  "Go then, there are other worlds than these.",
  "And so it goes.",
  "All this happened, more or less.",
  "It is only with the heart that one can see rightly.",
  "What is essential is invisible to the eye.",
  "The world is full of obvious things.",
  "Real courage is when you know you are licked.",
  "The world breaks everyone.",
  "I am haunted by humans.",
  "Memories warm you up from the inside.",
  "It does not do to dwell on dreams and forget to live.",
  "Happiness can be found in the darkest of times.",
  "It is our choices that show what we truly are.",
  "Moonlight drowns out all but the brightest stars.",
  "I am large, I contain multitudes.",
  "I celebrate myself, and sing myself.",
  "The woods are lovely, dark and deep.",
  "Miles to go before I sleep.",
  "Because I could not stop for Death.",
  "All happy families are alike.",
  "Happy families are all alike.",
  "To strive, to seek, to find, and not to yield.",
  "There is no charm equal to tenderness of heart.",
]
